CREATE TABLE [dbo].[Vote](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[IdCandidate] [bigint] NOT NULL,
	[IdVoter] [bigint] NOT NULL,
 CONSTRAINT [PK_Vote] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Vote]  WITH CHECK ADD  CONSTRAINT [FkCandidate] FOREIGN KEY([IdCandidate])
REFERENCES [dbo].[Person] ([Id])
GO

ALTER TABLE [dbo].[Vote] CHECK CONSTRAINT [FkCandidate]
GO

ALTER TABLE [dbo].[Vote]  WITH CHECK ADD  CONSTRAINT [FkVoter] FOREIGN KEY([IdVoter])
REFERENCES [dbo].[Person] ([Id])
GO

ALTER TABLE [dbo].[Vote] CHECK CONSTRAINT [FkVoter]
GO